server:
  port: 8080
  contextPath: /gateway
spring:
  profiles:
    active: oauth2,swagger
  application:
    name: spring-cloud-example-gateway
zuul:
  ignoredServices: '*'
  routes:
    uaa:
      path: /uaa/**
      sensitive-headers:
      stripPrefix: false
      serviceId: spring-cloud-example-security
    simple:
      path: /simple/**
      sensitive-headers:
      stripPrefix: false
      serviceId: spring-cloud-example-simaple
    feign:
      path: /feign/**
      sensitive-headers:
      stripPrefix: false
      serviceId: spring-cloud-example-feign
    legacy:
      path: /legacy/**
      url: http://127.0.0.1:8700/simple/legacy
    forward:
      path: /forward/**
      url: forward:/hello
