server:
  port: 8000
  contextPath: /uaa
spring:
  application:
    name: spring-cloud-example-security
  datasource:
    url: jdbc:mysql://192.168.32.124:3306/authority?useUnicode=true&characterEncoding=utf8
    username: root
    password: tmkj@zgb123
    driver-class-name: com.mysql.jdbc.Driver
security:
  ignored:
  - /resources/**
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: openid
      authorized-grant-types: authorization_code,refresh_token,password
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----
  form:
    enabled: true
    login-page: /login.html
    login-processing-url: /login
    default-success-url: /index.html
    parameters:
      username: username
      password: password