security:
  sessions: ALWAYS
  ignored: /favicon.ico,/jcaptcha,/webjars/**,/resources/**,/doc/**
  oauth2:
    client:
      accessTokenUri: http://localhost:8000/uaa/oauth/token
      userAuthorizationUri: http://localhost:8000/uaa/oauth/authorize
      clientId: acme
      clientSecret: a2105a35b309f5cf072dfe2a8c7ac233720ce04052741b9db5b1e595cc88ba4bb3c8534dca985b41
    resource:
      jwt:
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAnGp/Q5lh0P8nPL21oMMrt2RrkT9AW5jgYwLfSUnJVc9G6uR3cXRRDCjHqWU5WYwivcF180A6CWp/ireQFFBNowgc5XaA0kPpzEtgsA5YsNX7iSnUibB004iBTfU9hZ2Rbsc8cWqynT0RyN4TP1RYVSeVKvMQk4GT1r7JCEC+TNu1ELmbNwMQyzKjsfBXyIOCFU/E94ktvsTZUHF4Oq44DBylCDsS1k7/sfZC2G5EU7Oz0mhG8+Uz6MSEQHtoIi6mc8u64Rwi3Z3tscuWG2ShtsUFuNSAFNkY7LkLn+/hxLCu2bNISMaESa8dG22CIMuIeRLVcAmEWEWH5EEforTg+QIDAQAB
          -----END PUBLIC KEY-----