springfox:
  documentation: 
    swagger:
      v2:
        path: /api-docs
        info:
          version: ${project.version:project.parent.version}
          title: ${spring.application.name:project.artifactId} Api Documents
          description: ${project.description:The Springfox suite of java libraries are all about automating the generation of machine and human readable specifications for JSON APIs written using the spring family of projects.}